#!/bin/bash
FILES=files
rm -rf /opt/DataGrip
tar -xvf $FILES/datagrip/datagrip.tar.gz -C /opt
mv /opt/DataGrip-* /opt/DataGrip
ln -sf /opt/DataGrip/bin/datagrip.sh /usr/bin/datagrip.sh
cp -u -p $FILES/datagrip/DataGrip.desktop /usr/share/applications
